// English copy. Keep the shape identical to he.ts — the type is derived from this file.
export const en = {
  meta: {
    home: { title: "re:set pilates — Reformer Pilates in Hod Hasharon", desc: "Boutique Reformer Pilates in groups of five. Mat, private and duo sessions in Hod Hasharon." },
    schedule: { title: "Schedule — re:set pilates", desc: "Pick a class, a day and a bed. Reformer and Mat Pilates in Hod Hasharon." },
    services: { title: "Services — re:set pilates", desc: "Reformer small groups, Mat Pilates, private 1:1 and duo training." },
    pricing: { title: "Pricing — re:set pilates", desc: "Monthly memberships and class passes for re:set pilates." },
    about: { title: "The studio — re:set pilates", desc: "Five Reformer beds, one instructor, full attention. The re:set story." },
    faq: { title: "FAQ — Reformer Pilates questions, answered", desc: "What Reformer Pilates is, who it suits, what to wear and how booking works." },
    contact: { title: "Contact — re:set pilates", desc: "WhatsApp, directions and contact details for re:set pilates, Hod Hasharon." },
    quiz: { title: "Find your class — re:set pilates", desc: "Three quick questions to find the Pilates format that fits you." },
    gift: { title: "Gift cards — re:set pilates", desc: "Give someone a reset. re:set pilates gift cards." },
  },
  common: {
    langSwitch: "עב",
    langName: "English",
    book: "Book a Reformer Class",
    bookShort: "Book",
    back: "Back",
    close: "Close",
    pending: "To be confirmed",
    sample: "Sample profile",
    demoData: "Sample schedule · live availability arrives with Arbox",
    min: "min",
    seeSchedule: "See schedule",
    requestSession: "Request a session",
    learnMore: "Learn more",
    directions: "Directions",
    byRequest: "By request",
    skip: "Skip to content",
    menu: "Menu",
    announcement: "Launch pricing · monthly plans valid for the launch month only",
    dows: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    dowsLong: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    today: "Today",
  },
  nav: {
    book: "Book",
    classes: "Classes",
    studio: "Studio",
    me: "Me",
    classesPricing: "Classes & pricing",
    bookTitle: "Book a class",
    home: "Home",
    schedule: "Schedule",
    services: "Services",
    pricing: "Pricing",
    about: "The studio",
    faq: "FAQ",
    contact: "Contact",
    mine: "My classes",
    myClasses: "My classes",
    profile: "Profile",
    gift: "Gift cards",
    quiz: "Find your class",
  },
  welcome: {
    supporting: "STRONG BODY · CALM MIND · HAPPIER YOU",
    explore: "Explore first",
  },
  home: {
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    eyebrow: "Boutique Reformer studio · Hod Hasharon",
    heroTitle: ["Reformer Pilates,", "in a room of five."],
    statHead: ["Five beds.", "Your full attention."],
    stats: [
      { n: "5 people", l: "Maximum per class" },
      { n: "All levels", l: "Every class adapts to you" },
      { n: "50 minutes", l: "Every session" },
    ],
    upcoming: "Upcoming classes",
    withInstructor: "with",
    allPlans: "All memberships & passes",
    newHereEyebrow: "New here?",
    newHereTitle: "Your first class, step by step",
    firstSteps: [
      { t: "Book any Reformer class", d: "Pick a time that suits you. No experience needed." },
      { t: "Arrive 10 minutes early", d: "Grip socks, comfy clothes, water. We'll show you the Reformer." },
      { t: "Move at your own pace", d: "Five beds, one instructor. Every exercise is adapted to you." },
    ],
    notSure: "Not sure which class?",
    askOrit: "Ask Orit",
    reviewsEyebrow: "From our members",
    reviewsPending: "Member reviews appear here once the first members share them.",
    googleTitle: "Reviews on Google",
    googleRead: "Read all reviews",
    googleWrite: "Leave a Google review",
    sampleBadge: "Sample — replace with a real Google review",
    emailUs: "Email us",
    ctaTitle: ["Your bed", "is waiting."],
    sayHello: "Say hello",
    sub: "Reformer Pilates in groups of five, in Hod Hasharon.",
    supporting: "Strong body · Calm mind · Happier you",
    scroll: "Scroll",
    nextClass: "Your next class",
    classesTitle: "Our classes",
    classesAll: "All services",
    whyEyebrow: "Why Reformer Pilates?",
    whyTitle: "Only 5 spots in every Reformer class",
    whyBody: "A small room changes everything. Your instructor sees every movement, adjusts every spring, and builds the class around the people in it.",
    storyEyebrow: "The studio",
    storyTitle: "More than a workout",
    storyBody: "Five beds, warm light and slow, precise movement. A room made for coming back to.",
    storyCta: "The re:set story",
    quizEyebrow: "New here?",
    quizTitle: "Find the class that fits you",
    quizBody: "Three quick questions. One clear recommendation.",
    quizCta: "Start",
    pricingEyebrow: "Memberships & passes",
    pricingTitle: "Come once a week, or every day",
    pricingCta: "See all pricing",
    scheduleEyebrow: "This week",
    scheduleTitle: "Coming up at the studio",
    scheduleCta: "Full schedule",
    teamEyebrow: "Your instructors",
    teamTitle: "One instructor. Five of you.",
    teamNote: "Sample profiles. Our full team is announced before opening.",
    reviewsTitle: "From the mat",
    reviewsEmpty: "Member reviews appear here once we have real ones to share.",
    giftEyebrow: "Gift cards",
    giftTitle: "Give someone a reset",
    giftBody: "A class pass or a custom amount, sent with your own note.",
    giftCta: "Send a gift card",
    visitEyebrow: "Visit",
    visitTitle: "Find us in Hod Hasharon",
  },
  faqShort: [
    { q: "What is a Reformer?", a: "A sliding carriage with springs and straps. The springs create resistance you can increase or ease, so every exercise adapts to you." },
    { q: "Why groups of five?", a: "So the instructor sees every movement you make. Corrections, adjustments and attention, every class." },
    { q: "I am a beginner. Is it for me?", a: "Yes. Each class is built around the level in the room, and the springs let you start gently." },
    { q: "What does it feel like?", a: "Slow, deep work. You leave feeling longer, steadier and calmer." },
  ],
  services: {
    title: "Our services",
    sub: "Boutique Pilates, in small groups or one to one.",
    forWho: "Who it is for",
    format: "Format",
    duration: "Length",
    capacity: "Group size",
    upTo: "Up to",
    items: {
      reformer: {
        name: "Reformer · Small Groups",
        short: "Reformer",
        meta: "5 beds · 50 min",
        desc: "Reformer training in a group of up to five. Spring resistance lets you work deep and precise, adapted to every level.",
        who: "Anyone who wants strength, length and control, from first-timers to experienced movers.",
        format: "Small group, one instructor, morning and evening classes.",
        tags: ["Up to 5", "Morning & evening", "All levels"],
      },
      mat: {
        name: "Mat Pilates",
        short: "Mat",
        meta: "Small group · 50 min",
        desc: "Mat work for core strength, mobility and posture. A great foundation and complement to Reformer sessions.",
        who: "Beginners building a base, and Reformer regulars who want more core work.",
        format: "Small group class on the mat.",
        tags: ["Core", "Mobility", "Posture"],
      },
      private: {
        name: "Private · 1:1",
        short: "Private",
        meta: "Personal · 50 min",
        desc: "A session built around you: your goals, your pace, and extra care where your body needs it.",
        who: "Anyone who wants full attention, a specific goal, or a gentle return to movement.",
        format: "One instructor, one client, by appointment.",
        tags: ["Tailored", "Flexible times"],
      },
      duo: {
        name: "Duo Training",
        short: "Duo",
        meta: "Two people · 50 min",
        desc: "For friends, partners, sisters, or mother and daughter. Two beds, one instructor.",
        who: "Two people who want to train together at a shared pace.",
        format: "Two clients, one instructor, by appointment.",
        tags: ["Friends", "Mother & daughter"],
      },
      women: {
        name: "Women-only group",
        short: "Women only",
        meta: "Privacy · Comfort",
        desc: "A women-only Pilates experience designed for comfort, privacy and a welcoming atmosphere.",
        who: "Women who prefer a private, women-centered setting.",
        format: "Closed group, scheduled by request.",
        tags: ["Women only", "Private atmosphere"],
      },
    },
  },
  schedule: {
    title: "Schedule",
    sub: "Pick a class, a day and a time.",
    closedDay: "No classes on this day. Pick another day or request a private session.",
    smallGroup: "Small group",
    privateDuo: "Private or Duo session",
    byAppointment: "By appointment · 50 minutes",
    request: "Request",
    spotsLeft: "spots left",
    lastSpot: "Last spot",
    full: "Full · waitlist",
    booked: "Booked",
  },
  klass: {
    time: "Time",
    length: "Length",
    instructor: "Instructor",
    chooseBed: "Choose your bed",
    bedOptional: "Optional. Leave it empty for any bed.",
    mirrorWall: "Mirror wall",
    anyBed: "Any bed",
    bed: "Bed",
    taken: "Taken",
    reserve: "Reserve my spot",
    waitlist: "Join the waitlist",
    waitJoined: "You are on the waitlist",
    waitNote: "We will let you know the moment a bed opens up.",
    payNote: "Paid with your membership or pass. No extra charge.",
    payNoteVisitor: "You will choose a membership or pass at checkout.",
    alreadyBooked: "You are booked for this class",
    notFound: "This class is no longer available.",
  },
  confirm: {
    title: "Confirm booking",
    classLbl: "Class",
    when: "When",
    bed: "Bed",
    payWith: "Payment",
    payMember: "Membership · included",
    payNone: "Purchase at booking",
    confirmBtn: "Confirm",
    questions: "Questions? Ask Orit",
    finishArbox: "Complete booking in Arbox",
    choosePlan: "Choose a plan",
    remind: "Remind me 2 hours before",
    policy: "Cancellation policy",
    bookedTitle: "Your spot is saved",
    bookedSub: "See you at the studio.",
    addCalendar: "Add to calendar",
    viewBookings: "View my classes",
  },
  pricing: {
    title: "Pricing",
    sub: "Memberships and passes for Reformer small groups.",
    monthly: "Monthly",
    passes: "Passes",
    popular: "Popular",
    validMonth: "Valid one month",
    perWeek: "per week",
    unlimited: "Unlimited",
    sessions: "sessions",
    perSession: "/ session",
    bonus: "+1 free at launch",
    validity: "Monthly plans are valid one month from purchase. Passes are valid two months.",
    pendingApproval: "Prices pending final approval",
    choose: "Choose",
    hidden: "Pricing will be published soon. Message us and we will send you the details.",
  },
  checkout: {
    title: "Checkout",
    summary: "Your plan",
    details: "Your details",
    name: "Full name",
    phone: "Phone",
    email: "Email",
    payment: "Payment",
    choosePay: "Choose how to pay",
    payArbox: "Pay through Arbox",
    payBit: "Pay with Bit",
    payCard: "Pay by card",
    demoPay: "Payment links are being connected. Until then, choosing a method completes a demo purchase with no charge.",
    total: "Total",
    doneTitle: "You are all set",
    doneSub: "Your plan is active. Time to book your first class.",
    doneCta: "Book a class",
    notFound: "This plan is not available.",
  },
  my: {
    title: "My classes",
    upcoming: "Upcoming",
    emptyTitle: "No classes booked yet",
    emptySub: "Pick a class from the schedule and save yourself a bed.",
    cancel: "Cancel",
    cancelAsk: "Cancel this class?",
    cancelYes: "Yes, cancel",
    keep: "Keep it",
    calendar: "Calendar",
    policy: "Cancellation policy",
    policyText: "Cancel at least 24 hours before class and the session returns to your plan.",
    history: "Past classes",
    waitlist: "Waitlist",
    leave: "Leave",
  },
  profile: {
    guest: "Welcome",
    guestSub: "Book as a guest, or choose a plan to become a member.",
    memberSince: "Member since",
    membership: "My membership",
    thisWeek: "This week",
    sessionsLeft: "sessions left",
    renews: "Renews",
    validUntil: "Valid until",
    manage: "Manage plan",
    noPlan: "No active plan",
    noPlanSub: "Choose a membership or pass to get started.",
    details: "Personal details",
    language: "Language",
    notifications: "Class reminders",
    on: "On",
    off: "Off",
    install: "Add to home screen",
    installHint: "In your browser menu, choose “Add to Home Screen” to install re:set as an app.",
    demo: "Demo: switch member / new visitor",
    name: "Maya Levi",
    firstName: "Maya",
  },
  about: {
    eyebrow: "The studio",
    headline: "More than a workout",
    p1: "re:set is a boutique Reformer Pilates studio in Hod Hasharon. Five beds, one instructor, and full attention for everyone in the room.",
    p2: "We believe in slow, precise movement, adapting every session to your level, and a warm atmosphere that makes you want to come back.",
    statBeds: "Reformer beds",
    statMin: "minutes per class",
    statPrivate: "private sessions",
    philosophyTitle: "How we teach",
    philosophy: [
      { t: "Precision first", d: "Fewer repetitions, done well. We slow down so every movement counts." },
      { t: "Built around you", d: "Springs, range and pace are adjusted to each person, every class." },
      { t: "A room that feels good", d: "Warm light, calm sound and a group small enough to know your name." },
    ],
    founder: "Founder",
    team: "Instructors",
    portraitSoon: "Portrait coming soon",
    press: "As seen in",
  },
  faq: {
    title: "Questions, answered",
    sub: "Everything worth knowing before your first class.",
    more: "Still wondering about something?",
    items: [
      { q: "What is Reformer Pilates?", a: "Pilates practiced on the Reformer: a bed-like frame with a sliding carriage, springs and straps. The springs add resistance or support, which makes movements both more challenging and more controlled than on the floor." },
      { q: "Who is it suitable for?", a: "Almost everyone. Sessions adapt to different ages, fitness levels and bodies. If you have an injury or a medical condition, check with your doctor first and tell your instructor before class." },
      { q: "Can beginners join?", a: "Yes. With only five people in the room, your instructor can guide you through the equipment and adjust each exercise to where you are." },
      { q: "What happens in a first session?", a: "You arrive a few minutes early, meet your instructor, and get a short introduction to the Reformer. The class then moves through a full-body sequence at a pace that lets you learn the basics." },
      { q: "How long is a class?", a: "Every session is 50 minutes." },
      { q: "How big are the groups?", a: "Reformer classes have five beds, so a maximum of five participants. That is the heart of how we work." },
      { q: "What should I wear and bring?", a: "Comfortable, fitted clothing you can move in, and grip socks. Bring a water bottle. Everything else is at the studio." },
      { q: "How does booking work?", a: "Choose a class and a day in the schedule, pick a bed if you like, and confirm. Your spot is saved to your membership or pass." },
      { q: "Memberships or passes: which is right for me?", a: "A monthly membership suits a steady weekly rhythm. A pass gives you a set number of sessions to use flexibly within two months." },
      { q: "Can I cancel or reschedule?", a: "Yes, from the My classes screen. Cancel at least 24 hours before class and the session goes back to your plan. Later cancellations and no-shows count as used." },
      { q: "Is there a women-only option?", a: "A women-only format, designed for comfort and privacy, is available by request. Message us and we will coordinate." },
      { q: "Do you offer Mat Pilates and private sessions?", a: "Yes. Mat Pilates runs as a small group class, and private 1:1 and duo sessions are available by appointment." },
    ],
  },
  contact: {
    title: "Contact",
    sub: "Happy to answer anything. WhatsApp is fastest.",
    whatsapp: "Message us on WhatsApp",
    whatsappSub: "Replies during studio hours",
    phone: "Phone",
    hours: "Hours",
    hoursBySchedule: "By class schedule",
    parking: "Parking & access",
    address: "Address",
    openMaps: "Open in Maps",
    mapTitle: "Map: re:set pilates, Gazit 1, Hod Hasharon",
    leadTitle: "Want us to call you?",
    leadSub: "Leave your details and we will set up your first class together. No spam.",
    fName: "Name",
    fPhone: "Phone",
    fInterest: "I am interested in",
    send: "Send",
    sent: "Your email is ready · tap send in your mail app",
    email: "Email",
    google: "Google",
    googleReview: "Review us on Google",
    follow: "Follow the studio",
  },
  quiz: {
    title: "Find your class",
    step: "Question",
    of: "of",
    q: [
      {
        q: "What brings you to Pilates?",
        options: [
          { id: "strength", label: "Strength and tone" },
          { id: "calm", label: "Calm and mobility" },
          { id: "care", label: "Returning to movement gently" },
          { id: "together", label: "Something to do together" },
        ],
      },
      {
        q: "How much Pilates have you done?",
        options: [
          { id: "none", label: "None yet" },
          { id: "some", label: "A few classes" },
          { id: "regular", label: "I practice regularly" },
        ],
      },
      {
        q: "How do you like to train?",
        options: [
          { id: "group", label: "In a small group" },
          { id: "solo", label: "One to one" },
          { id: "pair", label: "With one other person" },
        ],
      },
    ],
    resultEyebrow: "We recommend",
    why: {
      reformer: "A small Reformer group gives you strength work with close guidance, at any level.",
      mat: "Mat Pilates builds the core foundation and mobility you are looking for, in a relaxed small group.",
      private: "A private session lets your instructor build everything around your body and your pace.",
      duo: "Duo training gives the two of you a shared session with one instructor's full attention.",
    },
    again: "Start over",
  },
  gift: {
    title: "Gift cards",
    sub: "Give someone a reset.",
    choose: "Choose a gift",
    custom: "Custom amount",
    amount: "Amount (₪)",
    to: "Recipient's name",
    from: "Your name",
    note: "A personal note",
    notePh: "Something kind…",
    preview: "Preview",
    cardLine: "A gift for you",
    send: "Continue to payment",
    demoPay: "Demo checkout. No payment is taken.",
    doneTitle: "Gift card ready",
    doneSub: "In the live version the recipient gets it by message, with your note.",
    another: "Send another",
    shopEyebrow: "Studio shop",
    shopTitle: "Coming soon",
    shopBody: "Grip socks and studio essentials, chosen by our instructors.",
    notify: "Notify me",
    notified: "We will let you know",
  },
  chat: {
    open: "Chat with {name}",
    title: "Ask {name}",
    status: "Founder · usually replies within hours",
    greeting: "Hi, I'm Orit 👋 Ask me anything about classes, prices, booking, cancelling or the studio.",
    placeholder: "Type your question…",
    send: "Send",
    typing: "Typing",
    whatsapp: "WhatsApp Orit",
    leaveDetails: "Leave your details",
    waPrefill: "Hi Orit, I have a question about re:set pilates: ",
    note: "Instant answers from the studio's info. Not medical advice.",
  },
  footer: {
    tagline: "Reset Your Strength",
    explore: "Explore",
    studio: "Studio",
    follow: "Follow",
    rights: "All rights reserved.",
    newsletterTitle: "Studio notes",
    newsletterSub: "Schedule updates and openings. Nothing else.",
  },
};

export type Content = typeof en;
